version: '3'
services:
  app:
    container_name: kronologic-web-app
    image: kronologic-web-app
    build: .
    user: node # The user to run as in the container
    working_dir: /app
    ports:
      - 8080:8080
    command: node ./server.js
